#!/usr/bin/env python3
"""Validate and render current Attempt03 task dispositions (not hardware readiness)."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATES = {'NOT_STARTED', 'WIP', 'HOST_VERIFIED', 'TARGET_VERIFIED', 'BLOCKED_TARGET',
          'BLOCKED_SOURCE', 'DEFERRED', 'FAIL', 'INTERRUPTED'}

def validate(data: object, root: Path = ROOT) -> list[str]:
    errors: list[str] = []
    if not isinstance(data, dict) or data.get('schema') != 'gonken-current-state-v1':
        return ['CURRENT_STATE_SCHEMA']
    if data.get('physical_acceptance_claimed') is not False:
        errors.append('HOST_REGISTRY_CANNOT_GRANT_PHYSICAL_ACCEPTANCE')
    slots = data.get('slots')
    if not isinstance(slots, list) or not slots:
        return errors + ['CURRENT_STATE_EMPTY']
    seen: set[str] = set()
    for row in slots:
        if not isinstance(row, dict):
            errors.append('CURRENT_STATE_ROW'); continue
        identity = row.get('id')
        if not isinstance(identity, str) or not re.fullmatch(r'\d+\.\d+\.[A-Za-z0-9]+', identity) or identity in seen:
            errors.append('CURRENT_STATE_ID'); continue
        seen.add(identity)
        if row.get('status') not in STATES:
            errors.append(identity + ':INVALID_STATE')
        evidence = row.get('evidence')
        if not isinstance(evidence, list):
            errors.append(identity + ':INVALID_EVIDENCE'); continue
        if row.get('status') in {'HOST_VERIFIED', 'TARGET_VERIFIED'} and not evidence:
            errors.append(identity + ':EVIDENCE_REQUIRED')
        # Physical validation is deliberately not derived from this host registry.
        if identity.startswith(('47.', '49.')) and row.get('status') == 'HOST_VERIFIED':
            errors.append(identity + ':TARGET_SLOT_NOT_HOST_CLOSABLE')
        for path in evidence:
            if not isinstance(path, str) or Path(path).is_absolute() or '..' in Path(path).parts or not (root / path).is_file():
                errors.append(identity + ':EVIDENCE_PATH')
    if not isinstance(data.get('next_action'), str) or not data['next_action'].strip():
        errors.append('NEXT_ACTION_REQUIRED')
    return errors

def render(data: dict) -> str:
    counts = {s: sum(r['status'] == s for r in data['slots']) for s in sorted(STATES)}
    text = ['# GonKenLab current implementation state', '',
            'Generated by `python3 scripts/current_state.py`. Task status is not hardware readiness.', '',
            '**Lineage:** ' + data['lineage'], '**Plan:** ' + data['blueprint'],
            '**Package status:** ' + data['package_status'],
            '**Physical acceptance:** not claimed.', '',
            '**Next action:** ' + data['next_action'], '',
            'Counts: ' + ', '.join(f'{s}={v}' for s, v in counts.items() if v), '',
            '| Slot | Scope | Disposition |', '|---|---|---|']
    text.extend(f"| {r['id']} | {r['title'].replace('|','/')} | {r['status']} |" for r in data['slots'])
    return '\n'.join(text) + '\n'

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--root', type=Path, default=ROOT)
    args = parser.parse_args(argv)
    try:
        data = json.loads((args.root / 'docs/development/CURRENT_GATES.json').read_text())
        errors = validate(data, args.root)
        if errors:
            print('\n'.join(errors)); return 1
        expected = render(data)
        output = args.root / 'docs/CURRENT_STATE.md'
        if args.check:
            if not output.is_file() or output.read_text() != expected:
                print('CURRENT_STATE_RENDER_DRIFT'); return 1
        else:
            output.write_text(expected)
        print(f"CURRENT_STATE_VALID slots={len(data['slots'])} physical_acceptance=false")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print('CURRENT_STATE_INVALID:' + type(exc).__name__); return 1

if __name__ == '__main__':
    raise SystemExit(main())
