#!/usr/bin/env python3
"""Render, verify, and report the M2.3 dependency profiles without dependencies."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "requirements" / "profiles.toml"
HASH_RE = re.compile(r"^[0-9a-f]{64}$")
SAFE_VALUE_RE = re.compile(r"^[A-Za-z0-9_.+-]+$")


class DependencyError(RuntimeError):
    """Raised when dependency policy or generated locks are invalid."""


def load_manifest() -> dict[str, Any]:
    with MANIFEST.open("rb") as handle:
        manifest = tomllib.load(handle)
    if manifest.get("schema_version") != 1:
        raise DependencyError("unsupported requirements profile schema")
    return manifest


def _profile_lock_path(profile: dict[str, Any]) -> Path:
    relative = Path(profile["lock"])
    if relative.is_absolute() or ".." in relative.parts:
        raise DependencyError(f"unsafe lock path for {profile['id']}: {relative}")
    path = (ROOT / relative).resolve()
    requirements_root = (ROOT / "requirements").resolve()
    if path.parent != requirements_root or path.suffix != ".lock":
        raise DependencyError(f"lock must be a direct requirements/*.lock file: {relative}")
    return path


def render_lock(profile: dict[str, Any]) -> str:
    lines = [
        "# Generated by: python scripts/dependencies.py render",
        f"# Profile: {profile['id']}",
        "# Do not hand-edit; update requirements/profiles.toml and regenerate.",
        "--require-hashes",
        "--only-binary=:all:",
    ]
    for dependency in sorted(profile.get("dependencies", []), key=lambda item: item["name"]):
        name = dependency["name"]
        version = dependency["version"]
        if not SAFE_VALUE_RE.fullmatch(name) or not SAFE_VALUE_RE.fullmatch(version):
            raise DependencyError(f"unsafe package identity in {profile['id']}")
        artifacts = dependency.get("artifacts", [])
        if not artifacts:
            raise DependencyError(f"{profile['id']}:{name} has no artifact hashes")
        hashes: list[str] = []
        for artifact in sorted(artifacts, key=lambda item: item["filename"]):
            digest = artifact["sha256"]
            if not HASH_RE.fullmatch(digest):
                raise DependencyError(f"invalid SHA-256 for {artifact['filename']}")
            if name.replace("-", "_").lower() not in artifact["filename"].lower():
                raise DependencyError(f"artifact/package mismatch: {artifact['filename']}")
            hashes.append(digest)
        requirement = f"{name}=={version}"
        if len(hashes) == 1:
            lines.append(f"{requirement} --hash=sha256:{hashes[0]}")
        else:
            lines.append(requirement + " \\")
            for index, digest in enumerate(hashes):
                continuation = " \\" if index < len(hashes) - 1 else ""
                lines.append(f"    --hash=sha256:{digest}{continuation}")
    return "\n".join(lines) + "\n"


def validate_manifest(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    profiles = manifest.get("profiles", [])
    if not profiles:
        raise DependencyError("no installable dependency profiles")
    ids: set[str] = set()
    locks: set[Path] = set()
    for profile in profiles:
        profile_id = profile.get("id")
        if not profile_id or profile_id in ids:
            raise DependencyError(f"missing or duplicate profile id: {profile_id!r}")
        ids.add(profile_id)
        if profile.get("status") != "installable":
            raise DependencyError(f"installable profile {profile_id} has wrong status")
        lock = _profile_lock_path(profile)
        if lock in locks:
            raise DependencyError(f"duplicate lock path: {lock.relative_to(ROOT)}")
        locks.add(lock)
        for dependency in profile.get("dependencies", []):
            if not dependency.get("license") or dependency["license"].startswith("UNVERIFIED"):
                raise DependencyError(f"unverified license: {profile_id}:{dependency.get('name')}")
            if not str(dependency.get("source", "")).startswith("https://"):
                raise DependencyError(f"missing HTTPS source: {profile_id}:{dependency.get('name')}")
            python_tag = "cp" + str(profile["python"]).replace(".", "")
            architecture = str(profile["platform"]).rsplit("_", 1)[-1]
            for artifact in dependency.get("artifacts", []):
                filename = artifact["filename"]
                pure_python = re.search(r"-py[23](?:\.py3)?-none-any\.whl$", filename) is not None
                abi3_python = re.search(r"-cp3[0-9]-abi3-", filename) is not None
                if not pure_python and not abi3_python and python_tag not in filename:
                    raise DependencyError(
                        f"artifact/interpreter mismatch in {profile_id}: {filename}"
                    )
                if not pure_python and architecture not in filename:
                    raise DependencyError(
                        f"artifact/platform mismatch in {profile_id}: {filename}"
                    )

    blocked = manifest.get("blocked_profiles", [])
    for profile in blocked:
        if profile.get("status") != "blocked" or not profile.get("blockers"):
            raise DependencyError(f"blocked profile lacks blockers: {profile.get('id')}")
        if profile.get("lock"):
            raise DependencyError(f"blocked profile must not have a lock: {profile.get('id')}")

    required_ids = {
        "core-pi-trixie-py313",
        "dev-py312",
        "ui-pi-trixie-py313",
        "ui-dev-py312",
    }
    if not required_ids.issubset(ids):
        raise DependencyError(f"missing required profiles: {sorted(required_ids - ids)}")
    return profiles


def validate_project_policy(manifest: dict[str, Any]) -> None:
    with (ROOT / "pyproject.toml").open("rb") as handle:
        project = tomllib.load(handle)["project"]
    if project.get("dependencies") != []:
        raise DependencyError("maintained headless package must remain dependency-free at M2.3")
    extras = project.get("optional-dependencies", {})
    if extras != {"ui": ["pygame==2.6.1"]}:
        raise DependencyError("pyproject optional UI profile drifted")
    if (ROOT / "requirements.txt").exists():
        raise DependencyError("legacy root requirements.txt remains present")

    core = next(
        profile for profile in manifest["profiles"] if profile["id"] == "core-pi-trixie-py313"
    )
    core_text = render_lock(core).lower()
    if "pygame" in core_text or "openwakeword" in core_text:
        raise DependencyError("optional UI/wake dependency leaked into core")


def render(*, check: bool) -> None:
    manifest = load_manifest()
    profiles = validate_manifest(manifest)
    validate_project_policy(manifest)
    drift: list[str] = []
    for profile in profiles:
        path = _profile_lock_path(profile)
        expected = render_lock(profile)
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(expected, encoding="utf-8")
    if drift:
        raise DependencyError("generated lock drift: " + ", ".join(drift))
    action = "verified" if check else "rendered"
    print(f"{action} {len(profiles)} installable dependency profiles")


def report(*, json_output: bool) -> None:
    manifest = load_manifest()
    profiles = validate_manifest(manifest)
    validate_project_policy(manifest)
    rows: list[dict[str, str]] = []
    for profile in profiles:
        dependencies = profile.get("dependencies", [])
        if dependencies:
            for dependency in dependencies:
                rows.append(
                    {
                        "profile": profile["id"],
                        "status": profile["status"],
                        "dependency": f"{dependency['name']}=={dependency['version']}",
                        "license": dependency["license"],
                    }
                )
        else:
            rows.append(
                {
                    "profile": profile["id"],
                    "status": profile["status"],
                    "dependency": "(none)",
                    "license": "N/A",
                }
            )
    for profile in manifest.get("blocked_profiles", []):
        rows.append(
            {
                "profile": profile["id"],
                "status": profile["status"],
                "dependency": profile["candidate"],
                "license": "BLOCKED—see manifest",
            }
        )
    if json_output:
        print(json.dumps(rows, indent=2, sort_keys=True))
        return
    print("| Profile | Status | Dependency | License |")
    print("|---|---|---|---|")
    for row in rows:
        print(
            f"| {row['profile']} | {row['status']} | "
            f"{row['dependency']} | {row['license']} |"
        )


def manifest_digest() -> None:
    payload = MANIFEST.read_bytes()
    print(hashlib.sha256(payload).hexdigest())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    render_parser = subparsers.add_parser("render", help="render or verify lock files")
    render_parser.add_argument("--check", action="store_true")
    report_parser = subparsers.add_parser("report", help="emit the license/profile report")
    report_parser.add_argument("--json", action="store_true")
    subparsers.add_parser("digest", help="print the profile-manifest SHA-256")
    args = parser.parse_args(argv)
    try:
        if args.command == "render":
            render(check=args.check)
        elif args.command == "report":
            report(json_output=args.json)
        else:
            manifest_digest()
    except (DependencyError, KeyError, TypeError, tomllib.TOMLDecodeError) as exc:
        print(f"dependency profile error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
